# Custom Minecraft Server Kube for Podman
---
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2025-03-15T00:14:00Z"
  labels:
    app: minecraft-pod
  name: minecraft-pod
spec:
  containers:
    - name: proxy
      image: docker.io/itzg/mc-proxy:latest
      resources:
        limits:
          cpu: 1
          memory: 2Gi
      env:
        - name: TYPE
          value: VELOCITY
        - name: DEBUG
          value: FALSE
        - name: ENABLE_RCON
          value: FALSE
        - name: ICON
          value: /server-icon.png
        - name: MINECRAFT_VERSION
          value: 1.20.1
        # - name: PLUGINS
        #   value: |
        #     https://github.com/TCPShield/RealIP/releases/download/2.8.1/TCPShield-2.8.1.jar
      ports:
      - containerPort: 25577
        hostPort: 25565
      volumeMounts:
        - name: velocity-config
          mountPath: /config/velocity.toml:ro,Z
        - name: forwarding-secret
          mountPath: /config/forwarding.secret:ro,Z
        - name: proxy-data
          mountPath: /server:Z
        - name: icon
          mountpath: /server-icon.png:Z

    - name: server
      image: docker.io/itzg/minecraft-server:latest
      resources:
        limits:
          cpu: 2
          memory: 6Gi
      stdin: TRUE
      tty: TRUE
      volumeMounts:
      - name: minecraft-data
        mountPath: /data:Z
      - name: patches
        mountPath: /patches:Z
      # securityContext:
      #   capabilities:
      #     add:
      #     - CAP_NET_RAW
            
      env:
        # Server
        - name: ONLINE_MODE
          value: TRUE
        - name: MAX_PLAYERS
          value: 6
        # - name: OPS
        #   value: username, username
        - name: ENABLE_WHITELIST
          value: TRUE
        # - name: WHITELIST
        #   value: username, username
        - name: TZ
          value: America/New_York
        - name: EULA
          value: TRUE
        - name: PATCH_DEFINITIONS
          value: /patches
        - name: ENABLE_RCON
          value: FALSE
        - name: SNOOPER_ENABLED
          value: FALSE
        # - name: MAX_TICK_TIME
        #   value: -1
        # - name: ENABLE_AUTOPAUSE
        #   value: TRUE
        # - name: AUTOPAUSE_KNOCK_INTERFACE
        #   value: eth0
        # Minecraft Options
        - name: TYPE
          value: FABRIC
        - name: FABRIC_LOADER_VERSION
          value: 0.16.10
        - name: VERSION
          value: 1.20.1
        # Mods
        - name: MODRINTH_LOADER
          value: FABRIC
        - name: MODRINTH_PROJECTS
          value: |
            fabric-api
            fabric-language-kotlin
            fabricproxy-lite

            architectury-api
            cardinal-components-api
            do-api
            yungs-api

            cloth-config
            fzzy-config
            resourceful-config

            balm
            bookshelf-lib
            botarium
            creativecore
            collective
            dawn
            formations
            geckolib
            glitchcore:beta
            midnightlib
            moonlight
            playeranimator:beta
            resourceful-lib
            supermartijn642s-config-lib
            supermartijn642s-core-lib
            terrablender:beta
            trinkets
            txnilib
            yacl

            c2me-fabric:alpha
            chunky
            clumps
            debugify
            ferrite-core
            modernfix
            no-chat-reports
            noisium
            threadtweak
            vmp-fabric:alpha
            yosbr

            areas
            biomes-o-plenty:beta
            formations-overworld
            friends-and-foes
            friends-and-foes-beekeeper-hut-fabric
            friends-and-foes-flowery-mooblooms-fabric
            lovely_snails
            more-mob-variants
            naturalist
            promenade
            random-village-names
            repurposed-structures-fabric
            ribbits
            smarter-farmers-farmers-replant
            villager-names-serilum
            villagersplus

            carry-on
            crops-love-rain
            cycle-paintings
            dismount-entity
            double-doors
            extract-poison
            fallingtree
            followers-teleport-too
            furnace-recycle
            grindstone-sharper-tools
            kaffees_dual_ride
            lootr
            move-boats
            move-minecarts
            no-hostiles-around-campfire
            nutritious-milk
            pet-names
            villager-death-messages
            village-bell-recipe
            waystones
            yigd

            appleskin
            emi
            emi-loot
            jade
            jade-addons-fabric
            jei:beta
            just-enough-professions-jep:beta
            open-parties-and-claims:beta
            trade-cycling
            trashslot
            xaeros-minimap
            xaeros-world-map

            botany-pots
            botany-trees

            create-fabric:beta
            slice-and-dice
            createaddition:beta
            create-deco
            create-steam-n-rails
            create-enchantment-industry-fabric
            create-new-age
            interiors
            bellsandwhistles

            farmers-delight-refabricated
            expanded-delight:beta
            crate-delight
            storage-delight
            oceans-delight
            more-delight

            immersive-armors
            immersive-aircraft
            immersive-melodies

            lets-do-farm-charm
            lets-do-bakery-farmcharm-compat:beta
            lets-do-brewery-farmcharm-compat:beta
            lets-do-herbalbrews
            lets-do-vinery

            macaws-windows
            macaws-fences-and-walls
            macaws-furniture
            macaws-stairs
            macaws-trapdoors
            macaws-bridges
            macaws-lights-and-lamps
            macaws-paths-and-pavings
            macaws-doors
            macaws-roofs
            macaws-paintings

            ae2
            better-archeology
            clutter
            every-compat
            natures-compass
            explorers-compass
            travelersbackpack
            gliders
            small-ships:beta
            niftycarts
            trash-cans

            datapack:camps_castles_carriages
            datapack:repurposed-structures-farmers-delight-compat
            datapack:repurposed-structures-friends-and-foes-compat
            datapack:repurposed-structures-villagerplus-compat
            datapack:tidal-towns
            datapack:villager-transportation
    
  volumes:
    
    - name: minecraft-data
      persistentVolumeClaim:
        claimName: minecraft-data
    
    - name: fabric-proxy
      hostPath:
        type: File
        path: ./velocity/FabricProxy-Lite.toml

    - name: patches
      hostPath:
        type: Directory
        path: ./patches

    - name: icon
      hostPath:
        type: File
        path: ./icons/server-icon.png

    - name: velocity-config
      hostPath:
        type: File
        path: ./velocity/velocity.toml

    - name: forwarding-secret
      hostPath:
        type: File
        path: ./velocity/forwarding.secret

    - name: proxy-data
      persistentVolumeClaim:
        claimName: proxy-data
