# Custom Minecraft Server Kube for Podman
---
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2025-03-15T00:14:00Z"
  labels:
    app: minecraft-pod
  name: minecraft-pod
restartPolicy: never
spec:
  containers:
    - name: proxy
      image: docker.io/itzg/mc-proxy:java21
      resources:
        limits:
          cpu: 1
          memory: 1Gi
      env:
        - name: TYPE
          value: VELOCITY
        - name: DEBUG
          value: FALSE
        - name: ENABLE_RCON
          value: FALSE
        - name: ICON
          value: /server-icon.png
        - name: MINECRAFT_VERSION
          value: 1.20.1
        # - name: PLUGINS
        #   value: |
        #     https://github.com/TCPShield/RealIP/releases/download/2.8.1/TCPShield-2.8.1.jar
      ports:
        - containerPort: 25577
          hostPort: 25565
      volumeMounts:
        - name: velocity-config
          mountPath: /config/velocity.toml:ro,Z
        - name: forwarding-secret
          mountPath: /config/forwarding.secret:ro,Z
        - name: proxy-data
          mountPath: /server:Z
        - name: icon
          mountpath: /server-icon.png:Z
      securityContext:
        privileged: false
        allowPrivilegeEscalation: false
        readOnlyRootFilesystem: true
        capabilities:
          drop:
            - CAP_DAC_OVERRIDE
            - CAP_FOWNER
            - CAP_FSETID
            - CAP_NET_BIND_SERVICE
            - CAP_SETFCAP
            - CAP_SETPCAP
            - CAP_SYS_CHROOT

    - name: server
      image: docker.io/itzg/minecraft-server:java21
      resources:
        limits:
          memory: 6Gi
      stdin: TRUE
      tty: TRUE
      volumeMounts:
        - name: minecraft-data
          mountPath: /data:Z
        - name: patches
          mountPath: /patches:Z
      securityContext:
        capabilities:
          privileged: false
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          drop:
            - CAP_DAC_OVERRIDE
            - CAP_FOWNER
            - CAP_FSETID
            - CAP_NET_BIND_SERVICE
            - CAP_SETFCAP
            - CAP_SETPCAP
            - CAP_SYS_CHROOT

      env:
        # Server
        - name: ONLINE_MODE
          value: TRUE
        - name: MAX_PLAYERS
          value: 6
        # - name: OPS
        #   value: username, username
        - name: ENABLE_WHITELIST
          value: TRUE
        # - name: WHITELIST
        #   value: username, username
        - name: TZ
          value: America/New_York
        - name: EULA
          value: TRUE
        - name: PATCH_DEFINITIONS
          value: /patches
        - name: ENABLE_RCON
          value: FALSE
        - name: SNOOPER_ENABLED
          value: FALSE
        - name: MAX_MEMORY
          value: 4G
        # Minecraft Options
        - name: TYPE
          value: MODRINTH
        - name: MODRINTH_MODPACK
          value: sop
        - name: MODRINTH_LOADER
          value: FABRIC
        - name: VERSION
          value: 1.20.1
        # Mods
        - name: MODRINTH_PROJECTS
          value: |
            fabricproxy-lite
            crossstitch

            balm:7.3.24+fabric-1.20.1
            bookshelf-lib:20.2.13
            botarium:2.3.4
            cardinal-components-api:5.2.3
            collective:1.20.1-7.94-fabric+forge+neo
            fabric-language-kotlin:1.12.3+kotlin.2.0.21
            geckolib:4.7
            glitchcore:0.0.1.1
            lithostitched
            midnightlib
            moonlight:fabric_1.20-2.13.79
            smartbrainlib:1.15
            terrablender:3.0.1.10
            yacl:3.1.0+1.20-fabric
            yungs-api:1.20-Fabric-4.0.6

            chunky
            clumps
            debugify:1.20.1+2.0
            krypton:0.2.3

            appleskin:2.5.1+mc1.20
            jade:11.13.1+fabric
            jade-addons-fabric:5.4.0+fabric
            polymorph:z88tNWJh
            trinkets:3.7.2
            xaeros-minimap:25.2.0
            xaeros-world-map:1.39.4

            botany-pots:13.0.40
            botany-trees:9.0.18
            every-compat:1.20-2.7.24
            explorers-compass:1.20.1-2.2.3-fabric
            gliders:1.1.6+fabric
            immersive-aircraft:1.2.2+1.20.1
            immersive-melodies:0.4.0+1.20.1
            natures-compass:1.20.1-2.2.3-fabric
            niftycarts:20.1.3
            small-ships:2.0.0-b1.4
            travelersbackpack:1.20.1-9.1.29
            waystones:14.1.11+fabric-1.20.1
            datapack:villager-transportation

            bl4cks-sit:r27
            carry-on:2.1.2.7
            dismount-entity
            followers-teleport-too
            lootr:0.7.35.85
            no-hostiles-around-campfire
            nutritious-milk
            smarter-farmers-farmers-replant
            yigd:2.0.12
            datapack:veinminer

            critters-and-companions:2.2.2
            friends-and-foes:fabric-mc1.20.1-3.0.8
            friends-and-foes-flowery-mooblooms-fabric:fabric-mc1.20.1-2.0.2
            ribbits:3.0.4
            lovely_snails:1.1.3+1.20.1
            more-mob-variants:1.3.1
            naturalist:4.0.3
            pet-names
            sn0wfrogscapybaras:1.1.0-mc1.20.1
            villager-names-serilum

            areas:1.20.1-6.1-fabric+forge+neo
            biomes-o-plenty:19.0.0.95
            ct-overhaul-village
            immersive-structures
            random-village-names
            repurposed-structures-fabric
            datapack:camps_castles_carriages
            datapack:ctov-friends-and-foes-compat
            datapack:repurposed-structures-friends-and-foes-compat
            datapack:tidal-towns

            create-fabric:0.5.1-f-build.1417+mc1.20.1
            slice-and-dice:3.3.1
            create-deco:2.0.2-1.20.1-fabric
            create-steam-n-rails:1.6.4+fabric-mc1.20.1
            create-new-age:1.1.2
            interiors:0.5.3+fabric-mc1.20.1
            bellsandwhistles:0.4.5-mc1.20.1-fabric

            farmers-delight-refabricated:1.20.1-2.3.0
            storage-delight:25.03.09-1.20-fabric
            datapack:repurposed-structures-farmers-delight-compat

  volumes:
    - name: minecraft-data
      persistentVolumeClaim:
        claimName: minecraft-data

    - name: fabric-proxy
      hostPath:
        type: File
        path: ./velocity/FabricProxy-Lite.toml

    - name: patches
      hostPath:
        type: Directory
        path: ./patches

    - name: icon
      hostPath:
        type: File
        path: ./icons/server-icon.png

    - name: velocity-config
      hostPath:
        type: File
        path: ./velocity/velocity.toml

    - name: forwarding-secret
      hostPath:
        type: File
        path: ./velocity/forwarding.secret

    - name: proxy-data
      persistentVolumeClaim:
        claimName: proxy-data
